// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package proto;

public interface GetUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 userId = 1;</code>
   * @return The userId.
   */
  int getUserId();
}
