// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package proto;

public interface ListUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ListUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.User user = 1;</code>
   */
  java.util.List<proto.User> 
      getUserList();
  /**
   * <code>repeated .proto.User user = 1;</code>
   */
  proto.User getUser(int index);
  /**
   * <code>repeated .proto.User user = 1;</code>
   */
  int getUserCount();
  /**
   * <code>repeated .proto.User user = 1;</code>
   */
  java.util.List<? extends proto.UserOrBuilder> 
      getUserOrBuilderList();
  /**
   * <code>repeated .proto.User user = 1;</code>
   */
  proto.UserOrBuilder getUserOrBuilder(
      int index);
}
