// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package proto;

public interface ListUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ListUserRequest)
    com.google.protobuf.MessageOrBuilder {
}
