// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package proto;

public interface UpdateUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.UpdateUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.User user = 1;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.proto.User user = 1;</code>
   * @return The user.
   */
  proto.User getUser();
  /**
   * <code>.proto.User user = 1;</code>
   */
  proto.UserOrBuilder getUserOrBuilder();
}
