// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package proto;

/**
 * Protobuf type {@code proto.User}
 */
public  final class User extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.User)
    UserOrBuilder {
private static final long serialVersionUID = 0L;
  // Use User.newBuilder() to construct.
  private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private User() {
    titulo_ = "";
    endereco_ = "";
    tipo_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new User();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private User(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            titulo_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            endereco_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            tipo_ = s;
            break;
          }
          case 40: {

            numeroQuartos_ = input.readInt32();
            break;
          }
          case 48: {

            numeroGaragens_ = input.readInt32();
            break;
          }
          case 57: {

            areaConstruida_ = input.readDouble();
            break;
          }
          case 65: {

            areaTerreno_ = input.readDouble();
            break;
          }
          case 73: {

            preco_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.UserOuterClass.internal_static_proto_User_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.UserOuterClass.internal_static_proto_User_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.User.class, proto.User.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  public int getId() {
    return id_;
  }

  public static final int TITULO_FIELD_NUMBER = 2;
  private volatile java.lang.Object titulo_;
  /**
   * <code>string titulo = 2;</code>
   * @return The titulo.
   */
  public java.lang.String getTitulo() {
    java.lang.Object ref = titulo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      titulo_ = s;
      return s;
    }
  }
  /**
   * <code>string titulo = 2;</code>
   * @return The bytes for titulo.
   */
  public com.google.protobuf.ByteString
      getTituloBytes() {
    java.lang.Object ref = titulo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      titulo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENDERECO_FIELD_NUMBER = 3;
  private volatile java.lang.Object endereco_;
  /**
   * <code>string endereco = 3;</code>
   * @return The endereco.
   */
  public java.lang.String getEndereco() {
    java.lang.Object ref = endereco_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      endereco_ = s;
      return s;
    }
  }
  /**
   * <code>string endereco = 3;</code>
   * @return The bytes for endereco.
   */
  public com.google.protobuf.ByteString
      getEnderecoBytes() {
    java.lang.Object ref = endereco_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      endereco_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIPO_FIELD_NUMBER = 4;
  private volatile java.lang.Object tipo_;
  /**
   * <code>string tipo = 4;</code>
   * @return The tipo.
   */
  public java.lang.String getTipo() {
    java.lang.Object ref = tipo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tipo_ = s;
      return s;
    }
  }
  /**
   * <code>string tipo = 4;</code>
   * @return The bytes for tipo.
   */
  public com.google.protobuf.ByteString
      getTipoBytes() {
    java.lang.Object ref = tipo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tipo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUMEROQUARTOS_FIELD_NUMBER = 5;
  private int numeroQuartos_;
  /**
   * <code>int32 numeroQuartos = 5;</code>
   * @return The numeroQuartos.
   */
  public int getNumeroQuartos() {
    return numeroQuartos_;
  }

  public static final int NUMEROGARAGENS_FIELD_NUMBER = 6;
  private int numeroGaragens_;
  /**
   * <code>int32 numeroGaragens = 6;</code>
   * @return The numeroGaragens.
   */
  public int getNumeroGaragens() {
    return numeroGaragens_;
  }

  public static final int AREACONSTRUIDA_FIELD_NUMBER = 7;
  private double areaConstruida_;
  /**
   * <code>double areaConstruida = 7;</code>
   * @return The areaConstruida.
   */
  public double getAreaConstruida() {
    return areaConstruida_;
  }

  public static final int AREATERRENO_FIELD_NUMBER = 8;
  private double areaTerreno_;
  /**
   * <code>double areaTerreno = 8;</code>
   * @return The areaTerreno.
   */
  public double getAreaTerreno() {
    return areaTerreno_;
  }

  public static final int PRECO_FIELD_NUMBER = 9;
  private double preco_;
  /**
   * <code>double preco = 9;</code>
   * @return The preco.
   */
  public double getPreco() {
    return preco_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getTituloBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, titulo_);
    }
    if (!getEnderecoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, endereco_);
    }
    if (!getTipoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, tipo_);
    }
    if (numeroQuartos_ != 0) {
      output.writeInt32(5, numeroQuartos_);
    }
    if (numeroGaragens_ != 0) {
      output.writeInt32(6, numeroGaragens_);
    }
    if (areaConstruida_ != 0D) {
      output.writeDouble(7, areaConstruida_);
    }
    if (areaTerreno_ != 0D) {
      output.writeDouble(8, areaTerreno_);
    }
    if (preco_ != 0D) {
      output.writeDouble(9, preco_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getTituloBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, titulo_);
    }
    if (!getEnderecoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, endereco_);
    }
    if (!getTipoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, tipo_);
    }
    if (numeroQuartos_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, numeroQuartos_);
    }
    if (numeroGaragens_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, numeroGaragens_);
    }
    if (areaConstruida_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, areaConstruida_);
    }
    if (areaTerreno_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, areaTerreno_);
    }
    if (preco_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, preco_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.User)) {
      return super.equals(obj);
    }
    proto.User other = (proto.User) obj;

    if (getId()
        != other.getId()) return false;
    if (!getTitulo()
        .equals(other.getTitulo())) return false;
    if (!getEndereco()
        .equals(other.getEndereco())) return false;
    if (!getTipo()
        .equals(other.getTipo())) return false;
    if (getNumeroQuartos()
        != other.getNumeroQuartos()) return false;
    if (getNumeroGaragens()
        != other.getNumeroGaragens()) return false;
    if (java.lang.Double.doubleToLongBits(getAreaConstruida())
        != java.lang.Double.doubleToLongBits(
            other.getAreaConstruida())) return false;
    if (java.lang.Double.doubleToLongBits(getAreaTerreno())
        != java.lang.Double.doubleToLongBits(
            other.getAreaTerreno())) return false;
    if (java.lang.Double.doubleToLongBits(getPreco())
        != java.lang.Double.doubleToLongBits(
            other.getPreco())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + TITULO_FIELD_NUMBER;
    hash = (53 * hash) + getTitulo().hashCode();
    hash = (37 * hash) + ENDERECO_FIELD_NUMBER;
    hash = (53 * hash) + getEndereco().hashCode();
    hash = (37 * hash) + TIPO_FIELD_NUMBER;
    hash = (53 * hash) + getTipo().hashCode();
    hash = (37 * hash) + NUMEROQUARTOS_FIELD_NUMBER;
    hash = (53 * hash) + getNumeroQuartos();
    hash = (37 * hash) + NUMEROGARAGENS_FIELD_NUMBER;
    hash = (53 * hash) + getNumeroGaragens();
    hash = (37 * hash) + AREACONSTRUIDA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAreaConstruida()));
    hash = (37 * hash) + AREATERRENO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAreaTerreno()));
    hash = (37 * hash) + PRECO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPreco()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.User parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.User parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.User parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.User parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.User parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.User parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.User parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.User parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.User parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.User parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.User parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.User parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.User prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.User}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.User)
      proto.UserOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.UserOuterClass.internal_static_proto_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.UserOuterClass.internal_static_proto_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.User.class, proto.User.Builder.class);
    }

    // Construct using proto.User.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      titulo_ = "";

      endereco_ = "";

      tipo_ = "";

      numeroQuartos_ = 0;

      numeroGaragens_ = 0;

      areaConstruida_ = 0D;

      areaTerreno_ = 0D;

      preco_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.UserOuterClass.internal_static_proto_User_descriptor;
    }

    @java.lang.Override
    public proto.User getDefaultInstanceForType() {
      return proto.User.getDefaultInstance();
    }

    @java.lang.Override
    public proto.User build() {
      proto.User result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.User buildPartial() {
      proto.User result = new proto.User(this);
      result.id_ = id_;
      result.titulo_ = titulo_;
      result.endereco_ = endereco_;
      result.tipo_ = tipo_;
      result.numeroQuartos_ = numeroQuartos_;
      result.numeroGaragens_ = numeroGaragens_;
      result.areaConstruida_ = areaConstruida_;
      result.areaTerreno_ = areaTerreno_;
      result.preco_ = preco_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.User) {
        return mergeFrom((proto.User)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.User other) {
      if (other == proto.User.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getTitulo().isEmpty()) {
        titulo_ = other.titulo_;
        onChanged();
      }
      if (!other.getEndereco().isEmpty()) {
        endereco_ = other.endereco_;
        onChanged();
      }
      if (!other.getTipo().isEmpty()) {
        tipo_ = other.tipo_;
        onChanged();
      }
      if (other.getNumeroQuartos() != 0) {
        setNumeroQuartos(other.getNumeroQuartos());
      }
      if (other.getNumeroGaragens() != 0) {
        setNumeroGaragens(other.getNumeroGaragens());
      }
      if (other.getAreaConstruida() != 0D) {
        setAreaConstruida(other.getAreaConstruida());
      }
      if (other.getAreaTerreno() != 0D) {
        setAreaTerreno(other.getAreaTerreno());
      }
      if (other.getPreco() != 0D) {
        setPreco(other.getPreco());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.User parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.User) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object titulo_ = "";
    /**
     * <code>string titulo = 2;</code>
     * @return The titulo.
     */
    public java.lang.String getTitulo() {
      java.lang.Object ref = titulo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        titulo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string titulo = 2;</code>
     * @return The bytes for titulo.
     */
    public com.google.protobuf.ByteString
        getTituloBytes() {
      java.lang.Object ref = titulo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        titulo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string titulo = 2;</code>
     * @param value The titulo to set.
     * @return This builder for chaining.
     */
    public Builder setTitulo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      titulo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string titulo = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitulo() {
      
      titulo_ = getDefaultInstance().getTitulo();
      onChanged();
      return this;
    }
    /**
     * <code>string titulo = 2;</code>
     * @param value The bytes for titulo to set.
     * @return This builder for chaining.
     */
    public Builder setTituloBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      titulo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object endereco_ = "";
    /**
     * <code>string endereco = 3;</code>
     * @return The endereco.
     */
    public java.lang.String getEndereco() {
      java.lang.Object ref = endereco_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endereco_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string endereco = 3;</code>
     * @return The bytes for endereco.
     */
    public com.google.protobuf.ByteString
        getEnderecoBytes() {
      java.lang.Object ref = endereco_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endereco_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string endereco = 3;</code>
     * @param value The endereco to set.
     * @return This builder for chaining.
     */
    public Builder setEndereco(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      endereco_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string endereco = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndereco() {
      
      endereco_ = getDefaultInstance().getEndereco();
      onChanged();
      return this;
    }
    /**
     * <code>string endereco = 3;</code>
     * @param value The bytes for endereco to set.
     * @return This builder for chaining.
     */
    public Builder setEnderecoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      endereco_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tipo_ = "";
    /**
     * <code>string tipo = 4;</code>
     * @return The tipo.
     */
    public java.lang.String getTipo() {
      java.lang.Object ref = tipo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tipo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tipo = 4;</code>
     * @return The bytes for tipo.
     */
    public com.google.protobuf.ByteString
        getTipoBytes() {
      java.lang.Object ref = tipo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tipo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tipo = 4;</code>
     * @param value The tipo to set.
     * @return This builder for chaining.
     */
    public Builder setTipo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tipo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tipo = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTipo() {
      
      tipo_ = getDefaultInstance().getTipo();
      onChanged();
      return this;
    }
    /**
     * <code>string tipo = 4;</code>
     * @param value The bytes for tipo to set.
     * @return This builder for chaining.
     */
    public Builder setTipoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tipo_ = value;
      onChanged();
      return this;
    }

    private int numeroQuartos_ ;
    /**
     * <code>int32 numeroQuartos = 5;</code>
     * @return The numeroQuartos.
     */
    public int getNumeroQuartos() {
      return numeroQuartos_;
    }
    /**
     * <code>int32 numeroQuartos = 5;</code>
     * @param value The numeroQuartos to set.
     * @return This builder for chaining.
     */
    public Builder setNumeroQuartos(int value) {
      
      numeroQuartos_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numeroQuartos = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumeroQuartos() {
      
      numeroQuartos_ = 0;
      onChanged();
      return this;
    }

    private int numeroGaragens_ ;
    /**
     * <code>int32 numeroGaragens = 6;</code>
     * @return The numeroGaragens.
     */
    public int getNumeroGaragens() {
      return numeroGaragens_;
    }
    /**
     * <code>int32 numeroGaragens = 6;</code>
     * @param value The numeroGaragens to set.
     * @return This builder for chaining.
     */
    public Builder setNumeroGaragens(int value) {
      
      numeroGaragens_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numeroGaragens = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumeroGaragens() {
      
      numeroGaragens_ = 0;
      onChanged();
      return this;
    }

    private double areaConstruida_ ;
    /**
     * <code>double areaConstruida = 7;</code>
     * @return The areaConstruida.
     */
    public double getAreaConstruida() {
      return areaConstruida_;
    }
    /**
     * <code>double areaConstruida = 7;</code>
     * @param value The areaConstruida to set.
     * @return This builder for chaining.
     */
    public Builder setAreaConstruida(double value) {
      
      areaConstruida_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double areaConstruida = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAreaConstruida() {
      
      areaConstruida_ = 0D;
      onChanged();
      return this;
    }

    private double areaTerreno_ ;
    /**
     * <code>double areaTerreno = 8;</code>
     * @return The areaTerreno.
     */
    public double getAreaTerreno() {
      return areaTerreno_;
    }
    /**
     * <code>double areaTerreno = 8;</code>
     * @param value The areaTerreno to set.
     * @return This builder for chaining.
     */
    public Builder setAreaTerreno(double value) {
      
      areaTerreno_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double areaTerreno = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearAreaTerreno() {
      
      areaTerreno_ = 0D;
      onChanged();
      return this;
    }

    private double preco_ ;
    /**
     * <code>double preco = 9;</code>
     * @return The preco.
     */
    public double getPreco() {
      return preco_;
    }
    /**
     * <code>double preco = 9;</code>
     * @param value The preco to set.
     * @return This builder for chaining.
     */
    public Builder setPreco(double value) {
      
      preco_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double preco = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearPreco() {
      
      preco_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.User)
  }

  // @@protoc_insertion_point(class_scope:proto.User)
  private static final proto.User DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.User();
  }

  public static proto.User getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<User>
      PARSER = new com.google.protobuf.AbstractParser<User>() {
    @java.lang.Override
    public User parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new User(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<User> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<User> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.User getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

