// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package proto;

public final class UserOuterClass {
  private UserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CreateUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CreateUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CreateUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CreateUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DeleteUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_DeleteUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DeleteUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_DeleteUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GetUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_GetUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GetUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_GetUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ListUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ListUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ListUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ListUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UpdateUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UpdateUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UpdateUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UpdateUserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\005proto\"\255\001\n\004User\022\n\n\002id\030\001 \001(\005" +
      "\022\016\n\006titulo\030\002 \001(\t\022\020\n\010endereco\030\003 \001(\t\022\014\n\004ti" +
      "po\030\004 \001(\t\022\025\n\rnumeroQuartos\030\005 \001(\005\022\026\n\016numer" +
      "oGaragens\030\006 \001(\005\022\026\n\016areaConstruida\030\007 \001(\001\022" +
      "\023\n\013areaTerreno\030\010 \001(\001\022\r\n\005preco\030\t \001(\001\".\n\021C" +
      "reateUserRequest\022\031\n\004user\030\001 \001(\0132\013.proto.U" +
      "ser\"/\n\022CreateUserResponse\022\031\n\004user\030\001 \001(\0132" +
      "\013.proto.User\"#\n\021DeleteUserRequest\022\016\n\006use" +
      "rId\030\001 \001(\005\"$\n\022DeleteUserResponse\022\016\n\006userI" +
      "d\030\001 \001(\005\" \n\016GetUserRequest\022\016\n\006userId\030\001 \001(" +
      "\005\",\n\017GetUserResponse\022\031\n\004user\030\001 \001(\0132\013.pro" +
      "to.User\"\021\n\017ListUserRequest\"-\n\020ListUserRe" +
      "sponse\022\031\n\004user\030\001 \003(\0132\013.proto.User\".\n\021Upd" +
      "ateUserRequest\022\031\n\004user\030\001 \001(\0132\013.proto.Use" +
      "r\"/\n\022UpdateUserResponse\022\031\n\004user\030\001 \001(\0132\013." +
      "proto.User2\315\002\n\013UserService\022A\n\nCreateUser" +
      "\022\030.proto.CreateUserRequest\032\031.proto.Creat" +
      "eUserResponse\022A\n\nDeleteUser\022\030.proto.Dele" +
      "teUserRequest\032\031.proto.DeleteUserResponse" +
      "\0228\n\007GetUser\022\025.proto.GetUserRequest\032\026.pro" +
      "to.GetUserResponse\022;\n\010ListUser\022\026.proto.L" +
      "istUserRequest\032\027.proto.ListUserResponse\022" +
      "A\n\nUpdateUser\022\030.proto.UpdateUserRequest\032" +
      "\031.proto.UpdateUserResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_User_descriptor,
        new java.lang.String[] { "Id", "Titulo", "Endereco", "Tipo", "NumeroQuartos", "NumeroGaragens", "AreaConstruida", "AreaTerreno", "Preco", });
    internal_static_proto_CreateUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_CreateUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CreateUserRequest_descriptor,
        new java.lang.String[] { "User", });
    internal_static_proto_CreateUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_CreateUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CreateUserResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_proto_DeleteUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_DeleteUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_DeleteUserRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_proto_DeleteUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_DeleteUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_DeleteUserResponse_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_proto_GetUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_proto_GetUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_GetUserRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_proto_GetUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_proto_GetUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_GetUserResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_proto_ListUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_proto_ListUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ListUserRequest_descriptor,
        new java.lang.String[] { });
    internal_static_proto_ListUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_proto_ListUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ListUserResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_proto_UpdateUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_proto_UpdateUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UpdateUserRequest_descriptor,
        new java.lang.String[] { "User", });
    internal_static_proto_UpdateUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_proto_UpdateUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UpdateUserResponse_descriptor,
        new java.lang.String[] { "User", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
