// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package proto;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string titulo = 2;</code>
   * @return The titulo.
   */
  java.lang.String getTitulo();
  /**
   * <code>string titulo = 2;</code>
   * @return The bytes for titulo.
   */
  com.google.protobuf.ByteString
      getTituloBytes();

  /**
   * <code>string endereco = 3;</code>
   * @return The endereco.
   */
  java.lang.String getEndereco();
  /**
   * <code>string endereco = 3;</code>
   * @return The bytes for endereco.
   */
  com.google.protobuf.ByteString
      getEnderecoBytes();

  /**
   * <code>string tipo = 4;</code>
   * @return The tipo.
   */
  java.lang.String getTipo();
  /**
   * <code>string tipo = 4;</code>
   * @return The bytes for tipo.
   */
  com.google.protobuf.ByteString
      getTipoBytes();

  /**
   * <code>int32 numeroQuartos = 5;</code>
   * @return The numeroQuartos.
   */
  int getNumeroQuartos();

  /**
   * <code>int32 numeroGaragens = 6;</code>
   * @return The numeroGaragens.
   */
  int getNumeroGaragens();

  /**
   * <code>double areaConstruida = 7;</code>
   * @return The areaConstruida.
   */
  double getAreaConstruida();

  /**
   * <code>double areaTerreno = 8;</code>
   * @return The areaTerreno.
   */
  double getAreaTerreno();

  /**
   * <code>double preco = 9;</code>
   * @return The preco.
   */
  double getPreco();
}
